language: go

os:
  - linux

before_install:
  - make debs

after_success:
  - codecov

go:
  - 1.8
  - 1.9.2
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - go test -cpu=2 -race -v $(go list ./... | grep -v vendor)
  - go test -cpu=2 -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v vendor)

notifications:
  email: false